// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RanchoTaco.Data;


#nullable disable

namespace RANCHO_TACO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419054657_InicialSQLite")]
    partial class InicialSQLite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("RanchoTacoSQLite.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MasVendido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MasVendido = true,
                            Nombre = "Tacos al pastor",
                            Precio = 50m
                        },
                        new
                        {
                            Id = 2,
                            MasVendido = true,
                            Nombre = "Gringa",
                            Precio = 70m
                        },
                        new
                        {
                            Id = 3,
                            MasVendido = false,
                            Nombre = "Quesadilla",
                            Precio = 40m
                        });
                });

            modelBuilder.Entity("RanchoTacoSQLite.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@taco.com",
                            EsAdmin = true,
                            Password = "1234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
